# Generated by Django 5.2.8 on 2025-11-12 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('tipo', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=20, verbose_name='Tipo')),
                ('raca', models.CharField(max_length=100, verbose_name='Raça')),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Idade (anos)')),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20, verbose_name='Porte')),
                ('personalidade', models.TextField(verbose_name='Personalidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Adoção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PetImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets/', verbose_name='Imagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='app.pet')),
            ],
            options={
                'verbose_name': 'Imagem do Pet',
                'verbose_name_plural': 'Imagens do Pet',
                'ordering': ['-principal', 'uploaded_at'],
            },
        ),
    ]
